name: Recently played games
on:
  # Schedule updates (everyday)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  metrics-steam:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:
    - uses: lowlighter/metrics@latest
      with:
        filename: metrics.plugin.steam.svg
        token: NOT_NEEDED
        base: ""
        plugin_steam_token: ${{ secrets.METRICS_STEAM_TOKEN }}
        plugin_steam: yes
        plugin_steam_user: "76561198844019686"
        plugin_steam_games_limit: 4
  
